name: PR CI

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.system.os }}
    strategy:
      matrix:
        rust_version:
        - stable
        # - beta
        node_version:
        - 16
        system:
        - os: macos-10.15
          target: x86_64-apple-darwin
        - os: ubuntu-20.04
          target: x86_64-unknown-linux-gnu
        - os: windows-latest
          target: x86_64-pc-windows-msvc
        include:
        - system:
            os:
            - self-hosted
            - macOS
            - ARM64
            target: aarch64-apple-darwin
          node_version: 16
          rust_version: stable

    steps:
    - name: Set LIBCLANG_PATH
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      if: matrix.config.os == 'windows-latest'
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
        cache: yarn
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust_version }}
        override: true
    - name: Install modules
      run: yarn install --ignore-scripts
    - name: Compile
      run: yarn run build
    - name: Run rust tests
      run: yarn run test:rust
    - name: Run node.js tests
      run: yarn run test:node
    - name: Check test coverage
      if: ${{ contains(matrix.system.os, 'ubuntu') && matrix.node_version == '16'
        && matrix.rust_version == 'stable' && github.base_ref != '' }}
      uses: anuraag016/Jest-Coverage-Diff@V1.4
      with:
        fullCoverageDiff: false
        delta: 0.2
        afterSwitchCommand: yarn install --ignore-scripts && yarn run compile